### ISSUE TITLE
auto macro overwrites.

### ISSUE THREAD

**Issue by dabunn** [CrossRealms/Splunk-Cyences-App-for-Splunk#428]
The macro  `cs_o365_success_login_outside_country_filter` is set at search * (the default) 
However there does not seem to be a logical way to change this.

The macro `cs_o365_failed_login_outside_country_filter` is edited by updating the "macro settings | o365 | cs_0365 failed login..." detail and then updating.

There does not seem to be a reciprocating option for cs_o365_success_login detail field.
Updating the macro directly simply sees it over written with the default "search *" some 5-mins later.

How do you update this macro?

**Comment by VatsalJagani** [comment]
@dabunn - You can just go to 

`From Cyences App` > `Splunk Settings` > `Saved Searches, Reports and Alerts page` > Select "O365 - Successful Login Outside Country" alert > Go to the end of the page and select `Cyences Notable Event Action` > Expand it and there you will be able to update it.

Not everyone understands macro, but everyone knows about alerts so you can update right where the alert is. That's the new feature we have implemented.

**Comment by dabunn** [comment]
So - Let me get this right
You update the failed login filter macro through the app interface as I describe above.
But; whilst the successful login macro exists, you can't update that, you edit the actual alert directly.

The problem with that is - the next release of the app will over write all the alerts setting them to default, that was the whole point about using macros.

**Comment by VatsalJagani** [comment]
@dabunn - No I meant in the alert action not directly under the alert query. That will not override on upgrade.
![image](https://github.com/CrossRealms/Splunk-Cyences-App-for-Splunk/assets/20964366/fbb1ab36-73ed-4d83-9e83-6494e62591bf)

**Comment by VatsalJagani** [comment]
@dabunn - Have you tried this way to update the filter?

**Comment by mahirchavda** [comment]
Closing the issue. Feel free to reopen if needed
