### ISSUE TITLE
Cisco ISE action field value always "failure"

### ISSUE THREAD

**Issue by 5tevebaker** [CrossRealms/Splunk-Cyences-App-for-Splunk#647]
I admit that I haven't spent much time with this application yet. I've run into the following configuration which caused a lot of issues with existing failed login alerts in our environment.

#################
#################
[cisco:ise:syslog]
EVAL-dest_category = if(MESSAGE_CODE IN (5400, 5401) AND isnull(AD_User_Candidate_Identities), "vpn_auth", dest_category)
EVAL-action = "failure"

Why is action set to "failure" for every ISE record?

**Comment by hardikhdholariya** [comment]
Hi @5tevebaker, thanks for reporting this issue. We updated the action field extraction as part of the PR: https://github.com/CrossRealms/Splunk-Cyences-App-for-Splunk/pull/685 

You'll see the fix in upcoming release.
